### ISSUE TITLE
Add hrk.roleName

### ISSUE THREAD

**Issue by justin-eckenweber** [CortexPE/HRKChat#1]
Would be nice to have more built-in placeholders like hrk.roleName

**Comment by CortexPE** [comment]
Isn't the chat & nametag formats per-role anyways though?

**Comment by justin-eckenweber** [comment]
Well there is no way to display the role name...

**Comment by CortexPE** [comment]
A player can have multiple roles, the way the plugin is set-up is:
```yml
chatFormat:
  # RoleID: "<{{hrk.displayName}}> {{msg}}"
  1: "<{{hrk.displayName}}> {{msg}}"
  2: "<{{hrk.displayName}}> {{msg}}"
```
(same for nametag format)

Why not just do it like this:
```yml
chatFormat:
  # RoleID: "<{{hrk.displayName}}> {{msg}}"
  1: "[Member] <{{hrk.displayName}}> {{msg}}"
  2: "[Operator] <{{hrk.displayName}}> {{msg}}"
```
