### ISSUE TITLE
Allow usage of names instead of strictly just IDs

### ISSUE THREAD

**Issue by CortexPE** [CortexPE/HRKChat#3]
Hierarchy nowadays allows you to use `name`s and role `ID`s or `roleName.ID` combos to fetch roles.

There is no need to make this thing less user-friendly by sticking to just IDs.

**Comment by Thunder33345** [comment]
what about name collisions since only ID is suppose to be unique

**Comment by CortexPE** [comment]
`roleName.ID` if the role name collides with another name
